/**
 * `clausroom-bridge join <blob>` — one-command bridge attach (onboarding v2).
 *
 * Decodes a base64url BridgeJoinBlob (from POST /api/rooms/:id/my-agent's
 * join_command), then writes ~/.clausroom/bridge.toml with SAFE LOCAL DEFAULTS
 * and prints (or runs) the token export + `claude mcp add` registration lines.
 *
 * SECURITY INVARIANT (see docs/API-CONTRACT.md §13): the blob carries CONNECTION
 * info plus the recipient's OWN bearer token only. It NEVER sets local security
 * config. This command therefore writes bridge.toml with read_only_default=true
 * and `filesystem.roots` = the directory the JOINING USER chooses (defaulting to
 * cwd) — never anything server-provided. The token is not stored in the config
 * file; it is printed as an `export AGENT_ROOM_BRIDGE_TOKEN=...` line (the config
 * references it via [room].token_env), delivered over the trusted in-app channel.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { stdin as input, stdout as output } from 'node:process';
import * as readline from 'node:readline/promises';
import { DEFAULTS, decodeJoinBlob, type BridgeJoinBlob } from '@clausroom/protocol';
import { ConfigError, DEFAULT_CONFIG_PATH, expandHome } from './config.js';

/** The bridge token env var name written as [room].token_env (contract §10/§13). */
const TOKEN_ENV = 'AGENT_ROOM_BRIDGE_TOKEN';

export interface JoinOptions {
  /** --config <path>: bridge.toml location (default ~/.clausroom/bridge.toml). */
  config?: string;
  /** --project <dir>: directory to expose as filesystem.roots (else prompt/cwd). */
  project?: string;
  /** --yes: assume defaults, overwrite an existing config without prompting. */
  yes?: boolean;
  /** --print: show what WOULD be written/run; touch nothing. */
  print?: boolean;
}

export interface JoinResult {
  /** Whether index.ts should run the existing `check` connectivity logic next. */
  runCheck: boolean;
  /** Config path (as the user would type it) to hand to runCheck. */
  configPath: string;
}

function isInteractive(): boolean {
  return Boolean(input.isTTY) && Boolean(output.isTTY);
}

async function ask(question: string, def: string): Promise<string> {
  const rl = readline.createInterface({ input, output });
  try {
    const answer = (await rl.question(`${question} [${def}]: `)).trim();
    return answer.length > 0 ? answer : def;
  } finally {
    rl.close();
  }
}

async function confirm(question: string): Promise<boolean> {
  const rl = readline.createInterface({ input, output });
  try {
    const answer = (await rl.question(`${question} [y/N]: `)).trim().toLowerCase();
    return answer === 'y' || answer === 'yes';
  } finally {
    rl.close();
  }
}

/** A short, human-readable description of a decode/validation failure. */
function describeDecodeError(err: unknown): string {
  if (
    err &&
    typeof err === 'object' &&
    'issues' in err &&
    Array.isArray((err as { issues?: unknown }).issues)
  ) {
    const issues = (err as { issues: Array<{ path?: unknown[]; message?: string }> }).issues
      .map((i) => `${(i.path ?? []).join('.') || '(blob)'}: ${i.message ?? 'invalid'}`)
      .join('; ');
    return `blob failed validation (${issues})`;
  }
  const raw = err instanceof Error ? err.message : String(err);
  // Normalize the codec's own "Invalid join blob: …." so it doesn't read doubled.
  return raw.replace(/^invalid join blob:\s*/i, '').replace(/\.\s*$/, '');
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
}

function osUsername(): string {
  try {
    return os.userInfo().username ?? '';
  } catch {
    return '';
  }
}

function defaultBridgeName(): string {
  const host = slug((os.hostname() || '').split('.')[0] ?? '');
  return host ? `${host}-bridge` : 'clausroom-dev-bridge';
}

/** TOML string literal (basic, double-quoted, JSON-compatible escaping). */
function tomlStr(value: string): string {
  return JSON.stringify(String(value));
}

interface TomlParams {
  humanName: string;
  agentName: string;
  bridgeName: string;
  serverUrl: string;
  roomId: string;
  projectDir: string;
}

function buildBridgeToml(p: TomlParams): string {
  const lines = [
    '# clausroom bridge config — generated by `clausroom-bridge join`.',
    `# The bridge token is NEVER stored here: export it as ${TOKEN_ENV}`,
    '# (see the printed `export` line). It is YOUR OWN bearer credential.',
    '',
    '[identity]',
    `human_name  = ${tomlStr(p.humanName)}`,
    `agent_name  = ${tomlStr(p.agentName)}`,
    `bridge_name = ${tomlStr(p.bridgeName)}`,
    '',
    '[room]',
    `server_url = ${tomlStr(p.serverUrl)}`,
    `room_id    = ${tomlStr(p.roomId)}`,
    `token_env  = ${tomlStr(TOKEN_ENV)}`,
    '',
    '[policy]',
    '# Safe defaults: read-only, text replies allowed, uploads need YOUR approval.',
    'read_only_default                  = true',
    'allow_agent_to_send_text           = true',
    'allow_agent_to_upload_files        = false',
    'require_human_approval_for_uploads = true',
    `max_upload_bytes_without_approval  = ${DEFAULTS.REQUIRE_APPROVAL_BYTES}`,
    `max_upload_bytes_absolute          = ${DEFAULTS.MAX_UPLOAD_BYTES}`,
    '',
    '[filesystem]',
    '# The project directory YOU chose to expose (read-only by default).',
    `roots         = [${tomlStr(p.projectDir)}]`,
    'deny_globs    = []',
    'downloads_dir = "~/.clausroom/downloads"',
    '',
  ];
  return lines.join('\n');
}

function claudeOnPath(): boolean {
  const dirs = (process.env.PATH ?? '').split(path.delimiter);
  const names = process.platform === 'win32' ? ['claude.cmd', 'claude.exe', 'claude.bat', 'claude'] : ['claude'];
  for (const dir of dirs) {
    if (!dir) continue;
    for (const name of names) {
      const candidate = path.join(dir, name);
      try {
        if (process.platform === 'win32') {
          if (fs.existsSync(candidate)) return true;
        } else {
          fs.accessSync(candidate, fs.constants.X_OK);
          return true;
        }
      } catch {
        /* try the next candidate */
      }
    }
  }
  return false;
}

/**
 * Try to register the bridge as a Claude Code MCP server directly. The token is
 * baked into Claude's local MCP env (the recipient's own credential, on their
 * own machine). Returns true only when the registration succeeded; otherwise the
 * caller prints the copy-paste command instead.
 */
function registerClaude(
  token: string,
  configDisplay: string,
  out: (s: string) => void,
  warn: (s: string) => void,
): boolean {
  // On Windows the `claude` shim is a .cmd; spawning it without a shell is
  // brittle, so we prefer printing the copy-paste line there.
  if (process.platform === 'win32') return false;
  if (!claudeOnPath()) return false;
  const args = [
    'mcp',
    'add',
    '--transport',
    'stdio',
    'clausroom',
    '--env',
    `${TOKEN_ENV}=${token}`,
    '--',
    'npx',
    '-y',
    'clausroom-bridge',
    'mcp',
    '--config',
    configDisplay,
  ];
  const res = spawnSync('claude', args, { stdio: 'inherit' });
  if (res.error || res.status !== 0) {
    warn(
      `Could not run \`claude mcp add\` automatically` +
        `${res.error ? ` (${res.error.message})` : ` (exit ${res.status})`}. Register it manually:`,
    );
    return false;
  }
  out('Registered the "clausroom" MCP server with Claude Code.');
  return true;
}

/**
 * Execute `clausroom-bridge join <blob> [opts]`. Decodes the blob, resolves a
 * project dir + identity with safe defaults, then either prints (--print) or
 * writes ~/.clausroom/bridge.toml and prints the token export + `claude mcp add`
 * lines. On write, sets the token in this process's env and returns
 * `{ runCheck: true }` so the caller can validate connectivity via the existing
 * `check` logic. Throws ConfigError on any hard failure (bad blob, refused
 * overwrite).
 */
export async function runJoin(blobArg: string, opts: JoinOptions): Promise<JoinResult> {
  const out = (line: string) => process.stdout.write(`${line}\n`);
  const warn = (line: string) => process.stderr.write(`${line}\n`);

  // 1. Decode + validate the blob (connection info + this agent's own token).
  let blob: BridgeJoinBlob;
  try {
    blob = decodeJoinBlob(blobArg.trim());
  } catch (err) {
    throw new ConfigError(
      `Invalid join blob — ${describeDecodeError(err)}.\n` +
        'Expected the base64url blob from the room\'s "Add my agent" flow ' +
        '(the `npx -y clausroom-bridge join <blob>` command it prints).',
    );
  }

  // 2. Project directory to expose — chosen by the JOINING USER, never the blob.
  let projectRaw: string;
  if (opts.project && opts.project.length > 0) {
    projectRaw = opts.project;
  } else if (!opts.yes && isInteractive()) {
    projectRaw = await ask('Project directory to expose to your agent (read-only by default)', process.cwd());
  } else {
    projectRaw = process.cwd();
  }
  const projectDir = path.resolve(expandHome(projectRaw));

  if (projectDir === os.homedir()) {
    warn(`warning: exposing your home directory (${projectDir}) — prefer a specific project folder.`);
  }
  try {
    if (!fs.statSync(projectDir).isDirectory()) {
      warn(`warning: ${projectDir} is not a directory.`);
    }
  } catch {
    warn(`warning: ${projectDir} does not exist yet — create it before your agent reads from it.`);
  }

  // 3. Identity: agent_name from the blob (or prompt); human/bridge names derived.
  const humanName = osUsername() || 'Human';
  let agentName = blob.agent_name;
  if (!agentName) {
    const def = `${humanName}'s Agent`;
    agentName = !opts.yes && isInteractive() ? await ask('Agent display name', def) : def;
  }
  const bridgeName = defaultBridgeName();

  const configDisplay = opts.config && opts.config.length > 0 ? opts.config : DEFAULT_CONFIG_PATH;
  const configResolved = path.resolve(expandHome(configDisplay));

  const tomlText = buildBridgeToml({
    humanName,
    agentName,
    bridgeName,
    serverUrl: blob.server_url,
    roomId: blob.room_id,
    projectDir,
  });

  const exportLine = `export ${TOKEN_ENV}="${blob.token}"`;
  const mcpAddLine =
    `claude mcp add --transport stdio clausroom --env ${TOKEN_ENV}=$${TOKEN_ENV} ` +
    `-- npx -y clausroom-bridge mcp --config ${configDisplay}`;

  // --print: show everything, write nothing, run nothing.
  if (opts.print) {
    out('# clausroom-bridge join --print: nothing was written or run.');
    out(`# Would write config to: ${configResolved}`);
    out('# ----- begin bridge.toml -----');
    out(tomlText.trimEnd());
    out('# ----- end bridge.toml -----');
    out('');
    out('# 1. Export your bridge token (your own bearer credential):');
    out(exportLine);
    out('');
    out('# 2. Register the bridge with your local coding agent:');
    out(mcpAddLine);
    return { runCheck: false, configPath: configDisplay };
  }

  // 4. Overwrite guard: never clobber an existing config without --yes / confirm.
  if (fs.existsSync(configResolved) && !opts.yes) {
    if (isInteractive()) {
      const ok = await confirm(`${configResolved} already exists. Overwrite?`);
      if (!ok) {
        throw new ConfigError(
          'Aborted: existing bridge.toml left unchanged. ' +
            'Re-run with --yes to overwrite, or --config <path> to write elsewhere.',
        );
      }
    } else {
      throw new ConfigError(
        `Refusing to overwrite existing ${configResolved} in non-interactive mode. ` +
          'Re-run with --yes to overwrite, or --config <path> to write elsewhere.',
      );
    }
  }

  // 5. Write the config with safe local defaults.
  fs.mkdirSync(path.dirname(configResolved), { recursive: true });
  fs.writeFileSync(configResolved, tomlText, 'utf8');
  try {
    fs.chmodSync(configResolved, 0o600);
  } catch {
    /* best-effort perms; non-fatal on platforms without POSIX modes */
  }
  out(`Wrote ${configResolved}`);

  // Make the token available to the connectivity check below (in-process only —
  // it is deliberately NOT written to the config file).
  process.env[TOKEN_ENV] = blob.token;

  out('');
  out(`Your bridge token (export it in any shell where you run the bridge):`);
  out(exportLine);
  out('');

  // 6. Register with Claude Code directly when possible; else print the command.
  const registered = registerClaude(blob.token, configDisplay, out, warn);
  if (!registered) {
    out('Register the bridge with your local coding agent (copy-paste):');
    out(mcpAddLine);
  }
  out('');
  out('Validating connectivity...');

  return { runCheck: true, configPath: configDisplay };
}
